// <auto-generated />
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Activities/sampleAuth/sampleAuth/Migrations/20260609082353_create.Designer.cs
========
using Blazor_Authentication_Sample.Data;
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Students/Sanjay/Blazor_Authentication_Sample/Blazor_Authentication_Sample/Migrations/20260623061500_Initial.Designer.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Activities/sampleAuth/sampleAuth/Migrations/20260609082353_create.Designer.cs
using sampleAuth.Models;

#nullable disable

namespace sampleAuth.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609082353_create")]
    partial class create
========

#nullable disable

namespace BlazorAuthenticationSample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623061500_Initial")]
    partial class Initial
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Students/Sanjay/Blazor_Authentication_Sample/Blazor_Authentication_Sample/Migrations/20260623061500_Initial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Activities/sampleAuth/sampleAuth/Migrations/20260609082353_create.Designer.cs
                .HasAnnotation("ProductVersion", "10.0.8")
========
                .HasAnnotation("ProductVersion", "7.0.0")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Students/Sanjay/Blazor_Authentication_Sample/Blazor_Authentication_Sample/Migrations/20260623061500_Initial.Designer.cs
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Activities/sampleAuth/sampleAuth/Migrations/20260609082353_create.Designer.cs
            modelBuilder.Entity("sampleAuth.Models.User", b =>
========
            modelBuilder.Entity("Blazor_Authentication_Sample.Data.Users", b =>
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Students/Sanjay/Blazor_Authentication_Sample/Blazor_Authentication_Sample/Migrations/20260623061500_Initial.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Activities/sampleAuth/sampleAuth/Migrations/20260609082353_create.Designer.cs
                    b.Property<string>("UserName")
========
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Students/Sanjay/Blazor_Authentication_Sample/Blazor_Authentication_Sample/Migrations/20260623061500_Initial.Designer.cs
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
