// <auto-generated />
using System;
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Workshop/Login/Login/Migrations/20260610185933_create1.Designer.cs
using Login.Model;
========
using Destination.Model;
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop1/DestinationAuth/Destination/Destination/Migrations/20260623044229_initial.Designer.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Workshop/Login/Login/Migrations/20260610185933_create1.Designer.cs
namespace Login.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610185933_create1")]
    partial class create1
========
namespace Destination.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623044229_initial")]
    partial class initial
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop1/DestinationAuth/Destination/Destination/Migrations/20260623044229_initial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Workshop/Login/Login/Migrations/20260610185933_create1.Designer.cs
                .HasAnnotation("ProductVersion", "10.0.9")
========
                .HasAnnotation("ProductVersion", "7.0.0")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop1/DestinationAuth/Destination/Destination/Migrations/20260623044229_initial.Designer.cs
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Workshop/Login/Login/Migrations/20260610185933_create1.Designer.cs
            modelBuilder.Entity("Login.Model.User", b =>
========
            modelBuilder.Entity("Destination.Model.Register", b =>
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop1/DestinationAuth/Destination/Destination/Migrations/20260623044229_initial.Designer.cs
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Workshop/Login/Login/Migrations/20260610185933_create1.Designer.cs
                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
========
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("Destination.Model.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartureDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop1/DestinationAuth/Destination/Destination/Migrations/20260623044229_initial.Designer.cs
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Workshop/Login/Login/Migrations/20260610185933_create1.Designer.cs
                    b.Property<string>("TelephoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
========
                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop1/DestinationAuth/Destination/Destination/Migrations/20260623044229_initial.Designer.cs
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
