// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Machinetest/TourManagement/TourManagement/Migrations/AppDbContextModelSnapshot.cs
using TourManagement.Models;
========
using TourManagement.Model;
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop3/TourManagement/TourManagement/Migrations/20260622102301_initials.Designer.cs

#nullable disable

namespace TourManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Machinetest/TourManagement/TourManagement/Migrations/AppDbContextModelSnapshot.cs
    partial class AppDbContextModelSnapshot : ModelSnapshot
========
    [Migration("20260622102301_initials")]
    partial class initials
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop3/TourManagement/TourManagement/Migrations/20260622102301_initials.Designer.cs
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Machinetest/TourManagement/TourManagement/Migrations/AppDbContextModelSnapshot.cs
                .HasAnnotation("ProductVersion", "10.0.9")
========
                .HasAnnotation("ProductVersion", "7.0.0")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop3/TourManagement/TourManagement/Migrations/20260622102301_initials.Designer.cs
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Machinetest/TourManagement/TourManagement/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("TourManagement.Models.Guide", b =>
========
            modelBuilder.Entity("TourManagement.Model.Destination", b =>
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop3/TourManagement/TourManagement/Migrations/20260622102301_initials.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("GuideName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Machinetest/TourManagement/TourManagement/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<string>("Langauage")
========
                    b.Property<string>("ImageUrl")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop3/TourManagement/TourManagement/Migrations/20260622102301_initials.Designer.cs
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guides");
                });

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Machinetest/TourManagement/TourManagement/Migrations/AppDbContextModelSnapshot.cs
            modelBuilder.Entity("TourManagement.Models.User", b =>
========
            modelBuilder.Entity("TourManagement.Model.Tour", b =>
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop3/TourManagement/TourManagement/Migrations/20260622102301_initials.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<<< HEAD:.NetCore/Razor/Sdudents/Arya/Razor/Machinetest/TourManagement/TourManagement/Migrations/AppDbContextModelSnapshot.cs
                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
========
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
>>>>>>>> 72d82c91693b9e35788e1e94f879a16858273e20:.NetCore/Blazor/Workshop/Workshop3/TourManagement/TourManagement/Migrations/20260622102301_initials.Designer.cs
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourManagement.Model.Tour", b =>
                {
                    b.HasOne("TourManagement.Model.Destination", "TDestination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TDestination");
                });

            modelBuilder.Entity("TourManagement.Model.Destination", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
